// jlang/src/sql_connection.cpp - java.sql.Connection, DatabaseMetaData, Savepoint,
// DriverManager and the connection pool (jlang::DataSource, commons-dbcp/commons-pool
// semantics). See jlang/Sql.h.
#include "sql_internal.h"

#include <mysql.h>

#include <atomic>
#include <cstdio>

namespace jlang {

using namespace sql_detail;

namespace {

// Connector/J MysqlSavepoint.
class MysqlSavepoint final : public Savepoint {
public:
    explicit MysqlSavepoint(const String& name) : name_(name) {}
    int32_t getSavepointId() override {
        throw SQLException(String("Only named savepoints are supported."), String("S1C00"));
    }
    String getSavepointName() override { return name_; }

private:
    String name_;
};

// Connector/J MysqlSavepoint.getUniqueId(): java.rmi.server.UID text with ':' and '-' -> '_'.
String uniqueSavepointName() {
    static std::atomic<int32_t> counter{-32768};
    static const int64_t unique = nowMillis() ^ (reinterpret_cast<intptr_t>(&counter) >> 4);
    char buf[80];
    std::snprintf(buf, sizeof buf, "_%x_%llx_%x", static_cast<unsigned>(unique & 0x7fffffff),
                  static_cast<unsigned long long>(nowMillis()), static_cast<unsigned>(counter.fetch_add(1) & 0xffff));
    return String(buf);
}

std::string quoteIdentifier(const String& name) {
    std::string r = "`";
    for (char c : std::string_view(name)) {
        if (c == '`') r += '`';
        r += c;
    }
    r += '`';
    return r;
}

}  // namespace

// ---------------------------------------------------------------------------------------
// Connection
Connection::Connection(Session* session, DataSource* pool) : session_(session), pool_(pool) {}

void Connection::throwClosed() {
    if (pool_ != nullptr) throw SQLException(String("Connection is closed."));
    throwSql("No operations allowed after connection closed.", "08003");
}

Session* Connection::session() {
    if (closed_ || session_ == nullptr) throwClosed();
    return session_;
}

String Connection::getURL() {
    return session_ != nullptr ? session_->cfg->url : String();
}

void Connection::registerStatement(Statement* s) {
    statements_.push_back(s);
}

void Connection::unregisterStatement(Statement* s) noexcept {
    for (size_t i = statements_.size(); i > 0; i--) {
        if (statements_[i - 1] == s) {
            statements_.erase(statements_.begin() + static_cast<std::ptrdiff_t>(i - 1));
            return;
        }
    }
}

Statement* Connection::createStatement() {
    return createStatement(ResultSet::TYPE_FORWARD_ONLY, ResultSet::CONCUR_READ_ONLY);
}

Statement* Connection::createStatement(int32_t resultSetType, int32_t resultSetConcurrency) {
    (void)session();
    auto* s = new Statement(this, resultSetType, resultSetConcurrency);
    registerStatement(s);
    return s;
}

PreparedStatement* Connection::prepareStatement(const String& sql) {
    return prepareStatement(sql, ResultSet::TYPE_FORWARD_ONLY, ResultSet::CONCUR_READ_ONLY);
}

PreparedStatement* Connection::prepareStatement(const String& sql, int32_t autoGeneratedKeys) {
    PreparedStatement* ps = prepareStatement(sql);
    if (autoGeneratedKeys == Statement::RETURN_GENERATED_KEYS) ps->setRetrieveGeneratedKeys(true);
    return ps;
}

PreparedStatement* Connection::prepareStatement(const String& sql, int32_t resultSetType, int32_t resultSetConcurrency) {
    (void)session();
    auto* ps = new PreparedStatement(this, sql, resultSetType, resultSetConcurrency);
    registerStatement(ps);
    return ps;
}

CallableStatement* Connection::prepareCall(const String& sql) {
    return prepareCall(sql, ResultSet::TYPE_FORWARD_ONLY, ResultSet::CONCUR_READ_ONLY);
}

CallableStatement* Connection::prepareCall(const String& sql, int32_t resultSetType, int32_t resultSetConcurrency) {
    (void)session();
    auto* cs = new CallableStatement(this, sql, resultSetType, resultSetConcurrency);
    registerStatement(cs);
    return cs;
}

void Connection::setAutoCommit(bool autoCommit) {
    Session* s = session();
    std::lock_guard<std::recursive_mutex> lk(s->mu);
    s->autoCommit = autoCommit;
    s->executeSimple(autoCommit ? "SET autocommit=1" : "SET autocommit=0");
}

bool Connection::getAutoCommit() {
    return session()->autoCommit;
}

void Connection::commit() {
    Session* s = session();
    if (s->autoCommit) throw SQLException(String("Can't call commit when autocommit=true"));
    try {
        s->executeSimple("commit");
    } catch (SQLException& e) {
        if (e.getSQLState().equals("08S01")) {
            throwSql("Communications link failure during commit(). Transaction resolution unknown.", "08007");
        }
        throw;
    }
}

void Connection::rollback() {
    Session* s = session();
    if (s->autoCommit) throwSql("Can't call rollback when autocommit=true", "08003");
    try {
        s->executeSimple("rollback");
    } catch (SQLException& e) {
        if (e.getSQLState().equals("08S01")) {
            throwSql("Communications link failure during rollback(). Transaction resolution unknown.", "08007");
        }
        throw;
    }
}

void Connection::rollback(Savepoint* savepoint) {
    Session* s = session();
    if (savepoint == nullptr) throw NullPointerException();
    try {
        s->executeSimple(str("ROLLBACK TO SAVEPOINT ", quoteIdentifier(savepoint->getSavepointName())));
    } catch (SQLException& e) {
        if (e.getSQLState().equals("08S01")) {
            throwSql("Communications link failure during rollback(). Transaction resolution unknown.", "08007");
        }
        throw;
    }
}

Savepoint* Connection::setSavepoint() {
    return setSavepoint(uniqueSavepointName());
}

Savepoint* Connection::setSavepoint(const String& name) {
    if (name.isNull() || name.length() == 0) throwSql("Savepoint name can not be NULL or empty", "S1009");
    Session* s = session();
    auto* sp = new MysqlSavepoint(name);
    s->executeSimple(str("SAVEPOINT ", quoteIdentifier(name)));
    return sp;
}

void Connection::releaseSavepoint(Savepoint* savepoint) {
    (void)savepoint;  // Connector/J 5.1: no-op
}

void Connection::setReadOnly(bool readOnly) {
    session()->readOnly = readOnly;
}

bool Connection::isReadOnly() {
    return session()->readOnly;
}

void Connection::setTransactionIsolation(int32_t level) {
    Session* s = session();
    const char* sql = nullptr;
    switch (level) {
        case TRANSACTION_NONE: throwSql("Transaction isolation level NONE not supported by MySQL", "S1C00");
        case TRANSACTION_READ_COMMITTED: sql = "SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED"; break;
        case TRANSACTION_READ_UNCOMMITTED: sql = "SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED"; break;
        case TRANSACTION_REPEATABLE_READ: sql = "SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ"; break;
        case TRANSACTION_SERIALIZABLE: sql = "SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE"; break;
        default: throwSql(str("Unsupported transaction isolation level '", level, "'"), "S1C00");
    }
    s->executeSimple(sql);
}

int32_t Connection::getTransactionIsolation() {
    Session* s = session();
    ExecResult* r;
    try {
        r = s->execute("SELECT @@session.transaction_isolation");
    } catch (SQLException& e) {
        if (e.getSQLState().equals("08S01")) throw;
        r = s->execute("SELECT @@session.tx_isolation");
    }
    if (r->rows == nullptr || r->rows->nrows == 0 || r->rows->lens[0] < 0) {
        throwSql("Could not retrieve transaction isolation level from server", "S1000");
    }
    std::string_view v(r->rows->data + r->rows->offs[0], static_cast<size_t>(r->rows->lens[0]));
    if (v == "READ-UNCOMMITTED") return TRANSACTION_READ_UNCOMMITTED;
    if (v == "READ-COMMITTED") return TRANSACTION_READ_COMMITTED;
    if (v == "REPEATABLE-READ") return TRANSACTION_REPEATABLE_READ;
    if (v == "SERIALIZABLE") return TRANSACTION_SERIALIZABLE;
    throwSql(str("Could not map transaction isolation '", std::string(v), " to a valid JDBC level."), "S1000");
}

void Connection::setCatalog(const String& catalog) {
    Session* s = session();
    if (catalog.isNull()) throwSql("Catalog can not be null", "S1009");
    s->executeSimple(str("USE ", quoteIdentifier(catalog)));
    s->catalog = catalog;
}

String Connection::getCatalog() {
    return String(session()->catalog);
}

DatabaseMetaData* Connection::getMetaData() {
    (void)session();
    return new DatabaseMetaData(this);
}

void Connection::close() noexcept {
    if (closed_) return;
    closed_ = true;
    try {
        std::vector<Statement*> open;
        open.swap(statements_);
        for (Statement* st : open) st->closeFromConnection();
    } catch (...) {
    }
    Session* s = session_;
    session_ = nullptr;
    if (s == nullptr) return;
    if (pool_ != nullptr) {
        pool_->returnSession(s);
    } else {
        s->close();
    }
}

bool Connection::isClosed() noexcept {
    return closed_ || session_ == nullptr || session_->isClosed();
}

bool Connection::isValid(int32_t timeoutSeconds) {
    if (isClosed()) return false;
    if (session_->ping(timeoutSeconds < 0 ? 0 : timeoutSeconds)) return true;
    session_->close();  // Connector/J abortInternal()
    return false;
}

// ---------------------------------------------------------------------------------------
// DatabaseMetaData
String DatabaseMetaData::getDatabaseProductName() {
    return "MySQL";
}
String DatabaseMetaData::getDatabaseProductVersion() {
    return conn_->session()->serverVersion;
}
int32_t DatabaseMetaData::getDatabaseMajorVersion() {
    return conn_->session()->major;
}
int32_t DatabaseMetaData::getDatabaseMinorVersion() {
    return conn_->session()->minor;
}
String DatabaseMetaData::getDriverName() {
    return "MySQL-AB JDBC Driver";
}
String DatabaseMetaData::getDriverVersion() {
    return str("mysql-connector-java-5.1.13 (jlang over MariaDB Connector/C ", mysql_get_client_info(), ")");
}
String DatabaseMetaData::getURL() {
    return conn_->session()->cfg->url;
}
String DatabaseMetaData::getUserName() {
    ExecResult* r = conn_->session()->execute("SELECT USER()");
    if (r->rows == nullptr || r->rows->nrows == 0 || r->rows->lens[0] < 0) return String();
    return String(r->rows->data + r->rows->offs[0], static_cast<size_t>(r->rows->lens[0]));
}

// ---------------------------------------------------------------------------------------
// DriverManager
namespace {
std::atomic<int32_t> g_loginTimeout{0};
}

Connection* DriverManager::getConnection(const String& url, const String& user, const String& password) {
    Config* cfg = Config::parse(url, user, password);
    if (cfg->connectTimeoutMs == 0 && g_loginTimeout.load() > 0) {
        cfg->connectTimeoutMs = static_cast<uint32_t>(g_loginTimeout.load()) * 1000u;
    }
    auto* s = new Session(cfg);
    s->connect();
    return new Connection(s, nullptr);
}

Connection* DriverManager::getConnection(const String& url) {
    return getConnection(url, String(), String());
}

void DriverManager::setLoginTimeout(int32_t seconds) {
    g_loginTimeout.store(seconds);
}

int32_t DriverManager::getLoginTimeout() {
    return g_loginTimeout.load();
}

// ---------------------------------------------------------------------------------------
// DataSource (GenericObjectPool + PoolableConnectionFactory + PoolingDataSource)
DataSource::DataSource(const String& url, const String& user, const String& password)
    : url_(url), user_(user), password_(password) {
    config_ = Config::parse(url, user, password);
}

Session* DataSource::createSession() {
    auto* s = new Session(config_);
    s->connect();
    return s;
}

void DataSource::destroySession(Session* s) noexcept {
    if (s != nullptr) s->close();
}

Connection* DataSource::getConnection() {
    const int64_t start = nowMillis();
    for (;;) {
        Session* s = nullptr;
        bool created = false;
        int64_t validationIdle = -1;
        bool defaultAutoCommit = true, defaultReadOnly = false;
        JSYNC(this) {
            validationIdle = validationIdleMillis_;
            defaultAutoCommit = defaultAutoCommit_;
            defaultReadOnly = defaultReadOnly_;
            for (;;) {
                if (closed_) throw IllegalStateException(String("Pool not open"));
                if (!idle_.empty()) {
                    s = idle_.front();
                    idle_.pop_front();
                    numActive_++;
                    break;
                }
                if (maxActive_ < 0 || numActive_ < maxActive_ || whenExhausted_ == WHEN_EXHAUSTED_GROW) {
                    numActive_++;
                    created = true;
                    break;
                }
                if (whenExhausted_ == WHEN_EXHAUSTED_FAIL) {
                    throw SQLException(String("Cannot get a connection, pool error Pool exhausted"));
                }
                try {
                    if (maxWait_ < 0) {
                        wait();
                    } else {
                        int64_t remaining = maxWait_ - (nowMillis() - start);
                        if (remaining <= 0) {
                            throw SQLException(String("Cannot get a connection, pool error Timeout waiting for idle object"));
                        }
                        wait(remaining);
                    }
                } catch (InterruptedException& e) {
                    sync::interrupt(sync::current());  // Thread.currentThread().interrupt()
                    throw SQLException(String("Cannot get a connection, general error"), e);
                }
            }
        }
        auto release = [this]() noexcept {
            JSYNC(this) {
                numActive_--;
                notifyAll();
            }
        };
        if (created) {
            try {
                s = createSession();
            } catch (...) {
                release();
                throw;
            }
        } else if (validationIdle >= 0 && nowMillis() - s->lastUsedMillis.load() > validationIdle && !s->ping(1)) {
            // jlang addition: drop sessions the server closed while they were idle.
            destroySession(s);
            release();
            continue;
        }
        // PoolableConnectionFactory.activateObject
        try {
            if (s->autoCommit != defaultAutoCommit) {
                std::lock_guard<std::recursive_mutex> lk(s->mu);
                s->autoCommit = defaultAutoCommit;
                s->executeSimple(defaultAutoCommit ? "SET autocommit=1" : "SET autocommit=0");
            }
            s->readOnly = defaultReadOnly;
        } catch (SQLException& e) {
            destroySession(s);
            release();
            if (created) {
                throw SQLException(str("Cannot get a connection, pool error Could not create a validated object, cause: ",
                                       e.getMessage()));
            }
            continue;
        }
        return new Connection(s, this);
    }
}

Connection* DataSource::getConnection(const String& user, const String& password) {
    (void)user;
    (void)password;
    throw UnsupportedOperationException(String());
}

void DataSource::returnSession(Session* s) noexcept {
    bool destroy = false;
    try {
        if (s->isClosed()) {
            destroy = true;  // dbcp: invalidateObject
        } else {
            // PoolableConnectionFactory.passivateObject
            std::lock_guard<std::recursive_mutex> lk(s->mu);
            if (!s->autoCommit && !s->readOnly) s->executeSimple("rollback");
            if (!s->autoCommit) {
                s->autoCommit = true;
                s->executeSimple("SET autocommit=1");
            }
        }
    } catch (...) {
        destroy = true;
    }
    try {
        JSYNC(this) {
            if (!destroy && (closed_ || (maxIdle_ >= 0 && static_cast<int32_t>(idle_.size()) >= maxIdle_))) {
                destroy = true;
            }
            if (!destroy) {
                s->lastUsedMillis = nowMillis();
                idle_.push_front(s);  // LIFO
            }
            numActive_--;
            notifyAll();
        }
    } catch (...) {
        destroy = true;
    }
    if (destroy) destroySession(s);
}

void DataSource::setMaxActive(int32_t maxActive) {
    JSYNC(this) {
        maxActive_ = maxActive;
        notifyAll();
    }
}
int32_t DataSource::getMaxActive() {
    JSYNC(this) { return maxActive_; }
    return 0;
}
void DataSource::setMaxIdle(int32_t maxIdle) {
    std::deque<Session*> excess;
    JSYNC(this) {
        maxIdle_ = maxIdle;
        while (maxIdle_ >= 0 && static_cast<int32_t>(idle_.size()) > maxIdle_) {
            excess.push_back(idle_.back());
            idle_.pop_back();
        }
        notifyAll();
    }
    for (Session* s : excess) destroySession(s);
}
int32_t DataSource::getMaxIdle() {
    JSYNC(this) { return maxIdle_; }
    return 0;
}
void DataSource::setMinIdle(int32_t minIdle) {
    JSYNC(this) { minIdle_ = minIdle; }
}
int32_t DataSource::getMinIdle() {
    JSYNC(this) { return minIdle_; }
    return 0;
}
void DataSource::setMaxWait(int64_t maxWaitMillis) {
    JSYNC(this) {
        maxWait_ = maxWaitMillis;
        notifyAll();
    }
}
int64_t DataSource::getMaxWait() {
    JSYNC(this) { return maxWait_; }
    return 0;
}
void DataSource::setWhenExhaustedAction(int8_t action) {
    if (action != WHEN_EXHAUSTED_FAIL && action != WHEN_EXHAUSTED_BLOCK && action != WHEN_EXHAUSTED_GROW) {
        throw IllegalArgumentException(str("whenExhaustedAction ", static_cast<int32_t>(action), " not recognized."));
    }
    JSYNC(this) {
        whenExhausted_ = action;
        notifyAll();
    }
}
int8_t DataSource::getWhenExhaustedAction() {
    JSYNC(this) { return whenExhausted_; }
    return 0;
}
void DataSource::setDefaultAutoCommit(bool v) {
    JSYNC(this) { defaultAutoCommit_ = v; }
}
bool DataSource::getDefaultAutoCommit() {
    JSYNC(this) { return defaultAutoCommit_; }
    return true;
}
void DataSource::setDefaultReadOnly(bool v) {
    JSYNC(this) { defaultReadOnly_ = v; }
}
bool DataSource::getDefaultReadOnly() {
    JSYNC(this) { return defaultReadOnly_; }
    return false;
}
void DataSource::setValidationIdleMillis(int64_t millis) {
    JSYNC(this) { validationIdleMillis_ = millis; }
}
int64_t DataSource::getValidationIdleMillis() {
    JSYNC(this) { return validationIdleMillis_; }
    return 0;
}

int32_t DataSource::getNumActive() {
    JSYNC(this) { return numActive_; }
    return 0;
}

int32_t DataSource::getNumIdle() {
    JSYNC(this) { return static_cast<int32_t>(idle_.size()); }
    return 0;
}

void DataSource::preparePool() {
    for (;;) {
        JSYNC(this) {
            if (closed_) throw IllegalStateException(String("Pool not open"));
            int32_t deficit = minIdle_ - static_cast<int32_t>(idle_.size());
            if (maxActive_ >= 0) {
                int32_t growLimit = maxActive_ - numActive_ - static_cast<int32_t>(idle_.size());
                if (growLimit < deficit) deficit = growLimit;
            }
            if (deficit <= 0) return;
        }
        Session* s = createSession();
        bool destroy = false;
        JSYNC(this) {
            if (closed_ || (maxIdle_ >= 0 && static_cast<int32_t>(idle_.size()) >= maxIdle_)) {
                destroy = true;
            } else {
                idle_.push_front(s);
                notifyAll();
            }
        }
        if (destroy) {
            destroySession(s);
            return;
        }
    }
}

void DataSource::close() noexcept {
    std::deque<Session*> toClose;
    JSYNC(this) {
        closed_ = true;
        toClose.swap(idle_);
        notifyAll();
    }
    for (Session* s : toClose) destroySession(s);
}

bool DataSource::isClosed() {
    JSYNC(this) { return closed_; }
    return true;
}

}  // namespace jlang
