// Tests for <jlang/Geom.h>: java.awt.Point / Rectangle / Polygon, with a parity table
// generated by jlang/tests/parity/PolyGen.java on JDK 21 (37,716 contains() results on 3,000
// random polygons, including int-overflowing coordinates, plus bounding boxes).
#include "jtest.h"

#include <jlang/Geom.h>

#include <string>

using namespace jlang;

#include "test_geom_cases.inc"

namespace {

struct Lcg {
    uint64_t seed;
    int32_t next() {
        seed = seed * 6364136223846793005ULL + 1442695040888963407ULL;
        return static_cast<int32_t>(seed >> 33);
    }
    // Java: lo + (int)((next() & 0x7fffffffL) % (hi - lo + 1))   (int arithmetic wraps)
    int32_t rnd(int32_t lo, int32_t hi) {
        int32_t span = static_cast<int32_t>(static_cast<uint32_t>(hi) - static_cast<uint32_t>(lo) + 1u);
        int64_t v = static_cast<int64_t>(static_cast<uint32_t>(next()) & 0x7fffffffu);
        int64_t m = span == -1 ? 0 : v % static_cast<int64_t>(span);
        return static_cast<int32_t>(static_cast<uint32_t>(lo) + static_cast<uint32_t>(static_cast<int32_t>(m)));
    }
};

std::string polyTranscript() {
    Lcg r{12345};
    std::string bits;
    int acc = 0, nb = 0;
    auto push = [&](bool v) {
        if (v) acc |= 1 << nb;
        nb++;
        if (nb == 4) {
            bits += "0123456789abcdef"[acc];
            acc = 0;
            nb = 0;
        }
    };
    for (int p = 0; p < 3000; p++) {
        int mode = p % 4;
        int32_t n = r.rnd(0, 9);
        auto* poly = new Polygon();
        int32_t span = mode == 0 ? 4 : mode == 1 ? 100 : mode == 2 ? 1000000000 : 2147483647;
        for (int i = 0; i < n; i++) {
            int32_t x, y;
            if (mode == 3) {
                x = r.next();
                y = r.next();
                if ((r.next() & 3) == 0) x = (r.next() & 1) == 0 ? INT32_MAX : INT32_MIN;
            } else {
                x = r.rnd(-span, span);
                y = r.rnd(-span, span);
            }
            poly->addPoint(x, y);
        }
        for (int t = 0; t < 12; t++) {
            bool res;
            int kind = t % 3;
            if (kind == 0) {
                int32_t x, y;
                if (mode == 0) {
                    x = r.rnd(-6, 6);
                    y = r.rnd(-6, 6);
                } else if (mode == 1) {
                    x = r.rnd(-110, 110);
                    y = r.rnd(-110, 110);
                } else if (n > 0 && (r.next() & 1) == 0) {
                    int32_t k = r.rnd(0, n - 1);
                    int32_t dx = r.rnd(-1, 1);
                    x = static_cast<int32_t>(static_cast<uint32_t>((*poly->xpoints)[k]) + static_cast<uint32_t>(dx));
                    int32_t dy = r.rnd(-1, 1);
                    y = static_cast<int32_t>(static_cast<uint32_t>((*poly->ypoints)[k]) + static_cast<uint32_t>(dy));
                } else {
                    x = r.next();
                    y = r.next();
                }
                res = poly->contains(x, y);
            } else if (kind == 1) {
                double x, y;
                if (mode == 0) {
                    x = r.rnd(-24, 24) / 4.0;
                    y = r.rnd(-24, 24) / 4.0;
                } else if (mode == 1) {
                    x = r.rnd(-440, 440) / 4.0;
                    y = r.rnd(-440, 440) / 4.0;
                } else {
                    double a = static_cast<double>(r.next());
                    a += r.rnd(0, 3) / 4.0;
                    x = a;
                    double b = static_cast<double>(r.next());
                    b += r.rnd(0, 3) / 4.0;
                    y = b;
                }
                res = poly->contains(x, y);
            } else {
                int32_t px = r.rnd(-6, 6);
                int32_t py = r.rnd(-6, 6);
                Point* pt = new Point(px, py);
                if (mode != 0) {
                    int32_t qx = r.rnd(-110, 110);
                    int32_t qy = r.rnd(-110, 110);
                    pt = new Point(qx, qy);
                }
                res = poly->contains(pt);
            }
            push(res);
        }
        if (p % 7 == 0) {
            int32_t ax = r.rnd(-span / 2, span / 2);
            int32_t ay = r.rnd(-span / 2, span / 2);
            poly->addPoint(ax, ay);
            for (int t = 0; t < 4; t++) {
                int32_t x = r.rnd(-6, 6);
                int32_t y = r.rnd(-6, 6);
                push(poly->contains(x, y));
            }
            Rectangle* b = poly->getBounds();
            bits += "|" + std::to_string(b->x) + "," + std::to_string(b->y) + "," + std::to_string(b->width) + "," +
                    std::to_string(b->height) + "|";
        }
    }
    if (nb > 0) bits += "0123456789abcdef"[acc];
    return bits;
}

}  // namespace

JTEST(GeomPolygonContainsParity) {
    std::string got = polyTranscript();
    std::string want = kPolyExpected;
    JCHECK_EQ(got.size(), want.size());
    size_t n = got.size() < want.size() ? got.size() : want.size();
    size_t first = std::string::npos;
    for (size_t i = 0; i < n; i++) {
        if (got[i] != want[i]) {
            first = i;
            break;
        }
    }
    if (first != std::string::npos) {
        size_t from = first > 40 ? first - 40 : 0;
        jtest::fail(__FILE__, __LINE__,
                    "polygon transcript differs at " + std::to_string(first) + ": got ..." + got.substr(from, 80) +
                        " want ..." + want.substr(from, 80));
    }
}

JTEST(GeomPolygonBasics) {
    auto* p = new Polygon();
    JCHECK_EQ(p->npoints, 0);
    JCHECK_EQ(p->xpoints->length, 4);
    JCHECK(!p->contains(0, 0));
    p->addPoint(0, 0);
    p->addPoint(10, 0);
    JCHECK(!p->contains(5, 0));  // < 3 points
    p->addPoint(10, 10);
    p->addPoint(0, 10);
    p->addPoint(0, 0);
    JCHECK_EQ(p->npoints, 5);
    JCHECK_EQ(p->xpoints->length, 8);  // grows to a power of two
    // half-open rules: left/top edges inside, right/bottom edges outside
    JCHECK(p->contains(0, 0));
    JCHECK(p->contains(5, 5));
    JCHECK(!p->contains(10, 5));
    JCHECK(!p->contains(5, 10));
    JCHECK(p->contains(0, 9));
    JCHECK(p->contains(9.999, 9.999));
    JCHECK(!p->contains(-0.001, 5.0));
    Rectangle* b = p->getBounds();
    JCHECK_EQ(b->x, 0);
    JCHECK_EQ(b->width, 10);
    JCHECK_EQ(b->toString(), String("java.awt.Rectangle[x=0,y=0,width=10,height=10]"));
    p->translate(5, 5);
    JCHECK(p->contains(5, 5));
    JCHECK(!p->contains(4, 4));
    JCHECK_EQ(p->getBounds()->x, 5);

    auto* xs = Array<int32_t>::of({0, 4, 4});
    auto* ys = Array<int32_t>::of({0, 0, 4});
    auto* tri = new Polygon(xs, ys, 3);
    JCHECK(tri->contains(3, 1));
    JCHECK(!tri->contains(1, 3));
    JCHECK_THROWS(IndexOutOfBoundsException, new Polygon(xs, ys, 4));
    JCHECK_THROWS(NegativeArraySizeException, new Polygon(xs, ys, -1));
}

JTEST(GeomPointAndRectangle) {
    auto* a = new Point(3, 4);
    auto* b = new Point(3, 4);
    JCHECK(a->equals(b));
    JCHECK_EQ(a->hashCode(), b->hashCode());
    // values from JDK 21
    JCHECK_EQ(a->hashCode(), -2114453504);
    JCHECK_EQ((new Point(1, 2))->hashCode(), -1048576);
    JCHECK_EQ(a->toString(), String("java.awt.Point[x=3,y=4]"));
    JCHECK_EQ(a->distance(0, 0), 5.0);
    a->setLocation(1.5, -1.5);
    JCHECK_EQ(a->x, 2);
    JCHECK_EQ(a->y, -1);

    // RectangleArea: new Rectangle() then add(Point) always includes (0,0).
    auto* r = new Rectangle();
    r->add(new Point(10, 20));
    r->add(new Point(15, 5));
    JCHECK_EQ(r->getMinX(), 0.0);
    JCHECK_EQ(r->getMaxX(), 15.0);
    JCHECK_EQ(r->getMinY(), 0.0);
    JCHECK_EQ(r->getMaxY(), 20.0);
    auto* r2 = new Rectangle(-1, -1, -1, -1);
    r2->add(7, 8);  // negative size: reset to the point
    JCHECK_EQ(r2->toString(), String("java.awt.Rectangle[x=7,y=8,width=0,height=0]"));
    auto* q = new Rectangle(0, 0, 10, 10);
    JCHECK(q->contains(0, 0));
    JCHECK(!q->contains(10, 10));
    JCHECK(q->intersects(new Rectangle(9, 9, 5, 5)));
    JCHECK(!q->intersects(new Rectangle(10, 0, 5, 5)));
    JCHECK_EQ(q->intersection(new Rectangle(5, 5, 10, 10))->toString(),
              String("java.awt.Rectangle[x=5,y=5,width=5,height=5]"));
    JCHECK_EQ(q->union_(new Rectangle(5, 5, 10, 10))->toString(),
              String("java.awt.Rectangle[x=0,y=0,width=15,height=15]"));
    // value from JDK 21
    JCHECK_EQ((new Rectangle(1, 2, 3, 4))->hashCode(), 70778880);
    auto* big = new Rectangle(INT32_MAX - 5, 0, 10, 10);  // right edge overflows
    JCHECK(big->contains(INT32_MAX - 1, 5));
}
