// Tests for <jlang/Regex.h>: a parity table of 128 Java patterns x 49 inputs (matches,
// lookingAt, find with groups and offsets, replaceAll/replaceFirst, split with limits)
// generated by jlang/tests/parity/RegexGen.java on JDK 21, plus API/exception checks.
#include "jtest.h"

#include <jlang/Regex.h>

#include <cstdio>
#include <string>

using namespace jlang;

#include "test_regex_cases.inc"

namespace {

std::string esc(const String& s) {
    std::string out;
    char buf[8];
    for (char16_t c : s.toUtf16()) {
        if (c >= 0x20 && c < 0x7f && c != '\\' && c != '"' && c != '|' && c != '[' && c != ']') {
            out.push_back(static_cast<char>(c));
        } else {
            std::snprintf(buf, sizeof buf, "\\u%04x", static_cast<unsigned>(c));
            out += buf;
        }
    }
    return out;
}

// Java can match the empty string between the two halves of a surrogate pair; UTF-8
// jlang::Strings have no such position (documented deviation).
bool knownDeviation(const std::string& want) {
    return want.find("\\ud83d<") != std::string::npos || want.find("\\ud83d]") != std::string::npos;
}

bool isAscii(const char* s) {
    for (; *s; s++)
        if (static_cast<unsigned char>(*s) >= 0x80) return false;
    return true;
}

std::string describe(Pattern* pat, const char* input) {
    String s(input);
    bool asc = isAscii(input);
    std::string r;
    Matcher* m = pat->matcher(s);
    r += "m" + std::to_string(m->matches() ? 1 : 0);
    m->reset();
    r += " l" + std::to_string(m->lookingAt() ? 1 : 0);
    m->reset();
    r += " f";
    int n = 0;
    while (m->find() && n < 8) {
        n++;
        r += "[";
        if (asc) r += std::to_string(m->start()) + "," + std::to_string(m->end()) + ":";
        r += esc(m->group());
        for (int g = 1; g <= m->groupCount(); g++) {
            String gs = m->group(g);
            r += "|" + (gs.isNull() ? std::string("null") : esc(gs));
        }
        r += "]";
    }
    r += " r:" + esc(pat->matcher(s)->replaceAll(String("<$0>")));
    r += " r1:" + esc(pat->matcher(s)->replaceFirst(String("_")));
    r += " s:";
    for (const String& x : *pat->split(s)) r += "[" + esc(x) + "]";
    r += " s-1:";
    for (const String& x : *pat->split(s, -1)) r += "[" + esc(x) + "]";
    r += " s2:";
    for (const String& x : *pat->split(s, 2)) r += "[" + esc(x) + "]";
    return r;
}

}  // namespace

JTEST(RegexParity) {
    const int np = static_cast<int>(sizeof kRegexPatterns / sizeof kRegexPatterns[0]);
    const int ni = static_cast<int>(sizeof kRegexInputs / sizeof kRegexInputs[0]);
    JCHECK_EQ(static_cast<size_t>(np * ni), sizeof kRegexExpected / sizeof kRegexExpected[0]);
    int failures = 0;
    for (int p = 0; p < np; p++) {
        Pattern* pat = nullptr;
        std::string err;
        try {
            pat = Pattern::compile(String(kRegexPatterns[p]));
        } catch (PatternSyntaxException& e) {
            err = std::string(e.getMessage());
        }
        for (int i = 0; i < ni; i++) {
            std::string want = kRegexExpected[p * ni + i];
            std::string got = pat == nullptr ? std::string("ERR") : describe(pat, kRegexInputs[i]);
            if (got != want && !knownDeviation(want)) {
                if (failures++ < 25)
                    jtest::fail(__FILE__, __LINE__,
                                std::string("pattern [") + kRegexPatterns[p] + "] -> [" + (pat ? std::string(pat->translated()) : err) +
                                    "] input [" + esc(String(kRegexInputs[i])) + "]\n      got  " + got + "\n      want " + want);
            }
        }
    }
    JCHECK_EQ(failures, 0);
}

JTEST(RegexSyntaxErrors) {
    const char* bad[] = {"a**", "a+*", "x{,2}", "{", "a{", "a{x}", "[", "(", "a{2,1}", "a{1", "\\", "*a", "+", "?",
                         "a{2}*", "\\0", "(?<1a>x)", "\\k<nope>", "\\p{NoSuchProperty}", ")", "[a-", "\\y"};
    for (const char* b : bad) {
        bool thrown = false;
        try {
            Pattern::compile(String(b));
        } catch (PatternSyntaxException& e) {
            thrown = true;
            JCHECK_EQ(e.getPattern(), String(b));
        }
        if (!thrown) jtest::fail(__FILE__, __LINE__, std::string("no PatternSyntaxException for ") + b);
    }
    try {
        Pattern::compile(String("a{"));
    } catch (PatternSyntaxException& e) {
        JCHECK_EQ(e.getDescription(), String("Illegal repetition"));
        JCHECK(e.getMessage().startsWith(String("Illegal repetition near index")));
    }
}

JTEST(RegexApi) {
    // config patterns (GSConfig / LegionConfig defaults)
    JCHECK(Pattern::compile(String("[a-zA-Z]{2,16}"))->matcher(String("Player"))->matches());
    JCHECK(!Pattern::compile(String("[a-zA-Z]{2,16}"))->matcher(String("Pl4yer"))->matches());
    JCHECK(!Pattern::compile(String("[a-zA-Z]{2,16}"))->matcher(String("Pl\xC3\xA9yer"))->matches());
    JCHECK(Pattern::compile(String(".*{2,255}"))->matcher(String("anything goes \xE4\xB8\xAD"))->matches());
    JCHECK(!Pattern::compile(String(".*{2,255}"))->matcher(String("two\nlines"))->matches());
    JCHECK(Pattern::matches(String("a+b"), String("aab")));
    Matcher* m = Pattern::compile(String("(?<k>\\w+)=(\\d+)"))->matcher(String("x=1, yy=22"));
    JCHECK(m->find());
    JCHECK_EQ(m->group(String("k")), String("x"));
    JCHECK_EQ(m->group(2), String("1"));
    JCHECK(m->find());
    JCHECK_EQ(m->start(), 5);
    JCHECK_EQ(m->end(1), 7);
    JCHECK(!m->find());
    JCHECK_THROWS(IllegalStateException, m->group());
    JCHECK_THROWS(IndexOutOfBoundsException, (m->reset(), m->find(), m->group(3)));
    JCHECK_THROWS(IllegalArgumentException, m->group(String("zz")));
    JCHECK_EQ(Pattern::compile(String("(\\w)(\\w)"))->matcher(String("ab cd"))->replaceAll(String("$2$1")), String("ba dc"));
    JCHECK_EQ(Pattern::compile(String("(?<a>x)"))->matcher(String("x"))->replaceAll(String("${a}${a}\\$")), String("xx$"));
    JCHECK_THROWS(IllegalArgumentException, Pattern::compile(String("x"))->matcher(String("x"))->replaceAll(String("$")));
    JCHECK_THROWS(IndexOutOfBoundsException, Pattern::compile(String("x"))->matcher(String("x"))->replaceAll(String("$2")));
    JCHECK_EQ(Pattern::compile(String("(a)"))->matcher(String("a"))->replaceAll(String("$10")), String("a0"));
    JCHECK_EQ(Matcher::quoteReplacement(String("a$b\\c")), String("a\\$b\\\\c"));
    JCHECK_EQ(Pattern::quote(String("a.b\\Ec")), String("\\Qa.b\\E\\\\E\\Qc\\E"));
    JCHECK(Pattern::compile(Pattern::quote(String("a.b")))->matcher(String("a.b"))->matches());
    JCHECK(!Pattern::compile(Pattern::quote(String("a.b")))->matcher(String("axb"))->matches());
    JCHECK(Pattern::compile(String("HELLO"), Pattern::CASE_INSENSITIVE)->matcher(String("hello"))->matches());
    JCHECK(Pattern::compile(String("a.b"), Pattern::LITERAL)->matcher(String("a.b"))->matches());
    JCHECK(Pattern::compile(String("^b$"), Pattern::MULTILINE)->matcher(String("a\nb\nc"))->find());
    JCHECK(Pattern::compile(String("a.b"), Pattern::DOTALL)->matcher(String("a\nb"))->matches());
    JCHECK(Pattern::compile(String(" a b # comment"), Pattern::COMMENTS)->matcher(String("ab"))->matches());
    // region
    Matcher* r = Pattern::compile(String("^b+$"))->matcher(String("abbbc"));
    r->region(1, 4);
    JCHECK(r->matches());
    JCHECK_EQ(r->group(), String("bbb"));
    JCHECK_THROWS(IndexOutOfBoundsException, r->region(3, 2));
    // find(int), appendReplacement/appendTail
    Matcher* f = Pattern::compile(String("\\d"))->matcher(String("a1b2c3"));
    JCHECK(f->find(3));
    JCHECK_EQ(f->start(), 3);
    auto* sb = new StringBuilder();
    f->reset();
    while (f->find()) f->appendReplacement(sb, String("#"));
    f->appendTail(sb);
    JCHECK_EQ(sb->toString(), String("a#b#c#"));
    // non-ASCII: byte offsets consistent with jlang::String
    Matcher* u = Pattern::compile(String("\xE4\xB8\xAD+"))->matcher(String("ab\xE4\xB8\xAD\xE4\xB8\xAD" "c"));
    JCHECK(u->find());
    JCHECK_EQ(u->start(), 2);
    JCHECK_EQ(u->end(), 8);
    JCHECK_EQ(String("ab\xE4\xB8\xAD\xE4\xB8\xAD" "c").substring(u->start(), u->end()), String("\xE4\xB8\xAD\xE4\xB8\xAD"));
    JCHECK_EQ(Pattern::compile(String(""))->matcher(String("\xC3\xA9"))->replaceAll(String("-")), String("-\xC3\xA9-"));
    JCHECK_EQ(Pattern::compile(String("x"))->toString(), String("x"));
    JCHECK_EQ(Pattern::compile(String("b"))->matcher(String("abc"))->toString(),
              String("java.util.regex.Matcher[pattern=b region=0,3 lastmatch=]"));
}
