// Tests for jlang::Properties / ResourceBundle: java.util.Properties.load (InputStream and
// Reader) and store() parity tables generated by jlang/tests/parity/PropGen.java on JDK 21.
#include "jtest.h"

#include <jlang/IO.h>

#include <algorithm>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace jlang;

#include "test_io_properties_cases.inc"

namespace {

std::string enc(const String& s) {
    std::string out;
    char buf[8];
    for (char16_t c : s.toUtf16()) {
        if (c >= 0x20 && c < 0x7f && c != '\\' && c != '|' && c != '"') {
            out.push_back(static_cast<char>(c));
        } else {
            std::snprintf(buf, sizeof buf, "\\u%04x", static_cast<unsigned>(c));
            out += buf;
        }
    }
    return out;
}

std::string dump(Properties* p) {
    std::vector<String> keys;
    for (const String& k : *p->stringPropertyNames()) keys.push_back(k);
    std::sort(keys.begin(), keys.end(), [](const String& a, const String& b) { return a.compareTo(b) < 0; });
    std::string out;
    for (const String& k : keys) out += enc(k) + "=" + enc(p->getProperty(k)) + "|";
    return out;
}

Array<int8_t>* bytesOf(const char* p, int32_t n) {
    auto* a = new Array<int8_t>(n);
    if (n > 0) std::memcpy(a->data(), p, static_cast<size_t>(n));
    return a;
}

std::string afterFirstLine(const std::string& s) {
    size_t nl = s.find('\n');
    return nl == std::string::npos ? std::string() : s.substr(nl + 1);
}

}  // namespace

JTEST(IOPropertiesLoadParity) {
    int i = 0;
    for (const PropCase& c : kPropCases) {
        std::string viaStream, viaReader;
        try {
            auto* p = new Properties();
            p->load(new ByteArrayInputStream(bytesOf(c.input, c.inputLen)));
            viaStream = dump(p);
        } catch (IllegalArgumentException&) {
            viaStream = "EX:IllegalArgumentException";
        }
        try {
            auto* p = new Properties();
            p->load(new InputStreamReader(new ByteArrayInputStream(bytesOf(c.input, c.inputLen)), String("ISO-8859-1")));
            viaReader = dump(p);
        } catch (IllegalArgumentException&) {
            viaReader = "EX:IllegalArgumentException";
        }
        if (viaStream != c.viaStream)
            jtest::fail(__FILE__, __LINE__, "case " + std::to_string(i) + " (stream): got [" + viaStream + "] want [" + c.viaStream + "]");
        if (viaReader != c.viaReader)
            jtest::fail(__FILE__, __LINE__, "case " + std::to_string(i) + " (reader): got [" + viaReader + "] want [" + c.viaReader + "]");
        i++;
    }
    JCHECK(i > 50);
}

JTEST(IOPropertiesStoreParity) {
    int i = 0;
    for (const StoreCase& c : kStoreCases) {
        auto* p = new Properties();
        p->setProperty(String(c.key), String(c.value));
        auto* sw = new StringWriter();
        p->store(sw, String());
        std::string w = afterFirstLine(std::string(sw->toString()));
        if (w != c.viaWriter) jtest::fail(__FILE__, __LINE__, "store(Writer) case " + std::to_string(i) + ": got [" + w + "]");
        auto* bo = new ByteArrayOutputStream();
        p->store(bo, String());
        Array<int8_t>* b = bo->toByteArray();
        std::string s = afterFirstLine(std::string(reinterpret_cast<const char*>(b->data()), static_cast<size_t>(b->length)));
        if (s != c.viaStream) jtest::fail(__FILE__, __LINE__, "store(OutputStream) case " + std::to_string(i) + ": got [" + s + "]");
        // round trip
        auto* q = new Properties();
        q->load(new ByteArrayInputStream(b));
        JCHECK_EQ(q->getProperty(String(c.key)), String(c.value));
        i++;
    }
    for (const CommentCase& c : kCommentCases) {
        auto* p = new Properties();
        auto* sw = new StringWriter();
        p->store(sw, String(c.comment));
        std::string out = std::string(sw->toString());
        // drop the date line (the last line)
        std::string body = out.substr(0, out.size() - 1);
        body = body.substr(0, body.rfind('\n') + 1);
        if (body != c.viaWriter) jtest::fail(__FILE__, __LINE__, "comment case: got [" + body + "] want [" + c.viaWriter + "]");
    }
}

JTEST(IOPropertiesApi) {
    auto* defs = new Properties();
    defs->setProperty(String("a"), String("1"));
    auto* p = new Properties(defs);
    JCHECK_EQ(p->getProperty(String("a")), String("1"));
    JCHECK(!p->containsKey(String("a")));  // defaults are not in the table
    JCHECK(p->getProperty(String("zz")).isNull());
    JCHECK_EQ(p->getProperty(String("zz"), String("d")), String("d"));
    JCHECK(p->setProperty(String("a"), String("2")).isNull());
    JCHECK_EQ(p->setProperty(String("a"), String("3")), String("2"));
    JCHECK_EQ(p->size(), 1);
    JCHECK_EQ(p->stringPropertyNames()->size(), 1);
    p->setProperty(String("b"), String("x"));
    JCHECK_EQ(p->toString(), String("{a=3, b=x}"));
    JCHECK_THROWS(NullPointerException, p->setProperty(String(), String("v")));
    auto* q = new Properties();
    q->putAll(p);
    JCHECK(q->equals(p));
    // PropertiesUtils.load(file) flow
    File* f = File::createTempFile(String("jlang"), String(".properties"));
    {
        auto* w = new FileWriter(f);
        w->write(String("# config\ngameserver.name = Aion \\\n    Lightning\nport:7777\nu=\\u00e9\n"));
        w->close();
    }
    auto* fis = new FileInputStream(f);
    auto* r = new Properties();
    r->load(fis);
    fis->close();
    JCHECK_EQ(r->getProperty(String("gameserver.name")), String("Aion Lightning"));
    JCHECK_EQ(r->getProperty(String("port")), String("7777"));
    JCHECK_EQ(r->getProperty(String("u")), String("\xC3\xA9"));
    // ResourceBundle
    auto* rb = new ResourceBundle(static_cast<InputStream*>(new FileInputStream(f)));
    JCHECK_EQ(rb->getString(String("port")), String("7777"));
    JCHECK(rb->containsKey(String("u")));
    JCHECK_THROWS(MissingResourceException, rb->getString(String("nope")));
    JCHECK(f->delete_());
}
