#!/usr/bin/env bash
# Regenerates jlang/tests/sql_oracle_expected.inc from SqlOracle.java (Connector/J 5.1.13).
# Needs a JDK, the mysql client and the local MariaDB server (user aion / password aion).
#
#   jlang/tests/java/gen_sql_oracle.sh
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../../.." && pwd)"
jar="$root/commons/lib/mysql-connector-java-5.1.13-bin.jar"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
javac -d "$work" -cp "$jar" "$here/SqlOracle.java"
run() {  # TZ zeroDateTimeBehavior
    mysql -h127.0.0.1 -uaion -paion -e "DROP DATABASE IF EXISTS jlang_test_oracle; CREATE DATABASE jlang_test_oracle"
    TZ="$1" java -Dfile.encoding=UTF-8 -cp "$work:$jar" SqlOracle "&zeroDateTimeBehavior=$2" 2>/dev/null
    mysql -h127.0.0.1 -uaion -paion -e "DROP DATABASE IF EXISTS jlang_test_oracle"
}
emit() {  # name file: raw string literal chunks (compilers limit literal sizes)
    echo "const char* const $1 ="
    awk 'BEGIN { n = 0; printf "R\"ORACLE(" } { print; n += length($0) + 1; if (n > 12000) { printf ")ORACLE\"\nR\"ORACLE("; n = 0 } } END { print ")ORACLE\";" }' "$2"
}
run UTC exception > "$work/utc.txt"
run Europe/Berlin exception > "$work/berlin.txt"
run UTC convertToNull > "$work/utc_ctn.txt"
run Europe/Berlin convertToNull > "$work/berlin_ctn.txt"
{
    echo "// Generated by jlang/tests/java/gen_sql_oracle.sh (Connector/J 5.1.13 + MariaDB); see test_sql_oracle.cpp."
    echo "// clang-format off"
    emit kOracleUtc "$work/utc.txt"
    emit kOracleBerlin "$work/berlin.txt"
    emit kOracleUtcCtn "$work/utc_ctn.txt"
    emit kOracleBerlinCtn "$work/berlin_ctn.txt"
} > "$here/../sql_oracle_expected.inc"
echo "wrote $here/../sql_oracle_expected.inc"
