// Generates jlang/tests/java_ref_data.inc: reference outputs of the JDK for the jlang parity
// tests (Float/Double.toString, String.format, java.util.Random, String.hashCode/split/
// compareTo, Math.round, Integer/Long parsing, Double.parseDouble ...).
//
//   cd jlang/tests/java && javac JavaRef.java && java JavaRef > ../java_ref_data.inc
import java.util.*;

public class JavaRef {
    static StringBuilder out = new StringBuilder();

    static String q(String s) {
        if (s == null) return "nullptr";
        StringBuilder b = new StringBuilder("\"");
        byte[] bytes = s.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        for (byte x : bytes) {
            int c = x & 0xFF;
            if (c == '"' || c == '\\') { b.append('\\').append((char) c); }
            else if (c >= 0x20 && c < 0x7F) b.append((char) c);
            else b.append(String.format("\\x%02x\" \"", c));
        }
        return b.append('"').toString();
    }

    static String d(double v) {
        if (Double.isNaN(v)) return "std::numeric_limits<double>::quiet_NaN()";
        if (Double.isInfinite(v)) return v > 0 ? "std::numeric_limits<double>::infinity()" : "-std::numeric_limits<double>::infinity()";
        return Double.toHexString(v);
    }

    static String f(float v) {
        if (Float.isNaN(v)) return "std::numeric_limits<float>::quiet_NaN()";
        if (Float.isInfinite(v)) return v > 0 ? "std::numeric_limits<float>::infinity()" : "-std::numeric_limits<float>::infinity()";
        return "std::bit_cast<float>(static_cast<int32_t>(" + Float.floatToRawIntBits(v) + "))";
    }

    public static void main(String[] args) {
        out.append("// Generated by jlang/tests/java/JavaRef.java with ").append(System.getProperty("java.version")).append(". Do not edit.\n");

        // ---- Double.toString
        double[] ds = {0.0, -0.0, 1.0, -1.0, 0.1, 0.2, 0.3, 1.0 / 3, 2.0 / 3, 100.0, 1e7, 9999999.0, 1e-3, 9.99e-4, 1.0e-4,
            123456789.0, 1e21, 1e22, 1e23, 2e23, 1.7976931348623157e308, 4.9e-324, 2.2250738585072014E-308, Math.PI, Math.E,
            0.5, 1.5, 12345.678, 1e-10, 3.0e10, 5e-324, 1.0e15, 1.23456789012e15, 0.001, 0.0010000001, 1234567.0,
            9007199254740993.0, 1e16, 100.5, 1e100, 1.1, 2.675, 0.15, 0.125, 0.375, -123.456,
            Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY};
        out.append("static const DoubleCase kDoubleToString[] = {\n");
        for (double v : ds) out.append("    {").append(d(v)).append(", ").append(q(Double.toString(v))).append("},\n");
        out.append("};\n");

        // ---- Float.toString
        float[] fs = {0.0f, -0.0f, 1.0f, -1.0f, 0.1f, 0.2f, 0.3f, 1.0f / 3, 100.0f, 1e7f, 9999999.0f, 1e-3f, 9.99e-4f,
            123456789.0f, 1e10f, 3.4028235e38f, 1.4e-45f, 1.17549435E-38f, (float) Math.PI, 0.5f, 1.5f, 12345.678f, 1e-10f,
            33.333332f, 16777216f, 16777217f, 2.5f, 0.15f, 1.1f, 4.35f, 100.5f, -45.25f,
            Float.NaN, Float.POSITIVE_INFINITY, Float.NEGATIVE_INFINITY};
        out.append("static const FloatCase kFloatToString[] = {\n");
        for (float v : fs) out.append("    {").append(f(v)).append(", ").append(q(Float.toString(v))).append("},\n");
        out.append("};\n");

        // ---- String.format (double argument)
        String[] dfmts = {"%f", "%.2f", "%.1f", "%.0f", "%10.3f", "%-10.3f|", "%010.2f", "%+.2f", "% .2f", "%,.2f",
            "%e", "%.3e", "%E", "%g", "%.3g", "%10.4g", "%(.2f", "%.10f", "%s"};
        double[] dargs = {0.0, -0.0, 1.0, 0.125, 0.15, 2.675, 1234567.891, -1234.5, 1e-5, 123456789.123, 0.5, 1.5, 2.5,
            9.995, 99.95, 1e20, 3.14159265358979, 0.0001234, 5e-7};
        out.append("static const FormatDoubleCase kFormatDouble[] = {\n");
        for (String fm : dfmts) for (double v : dargs)
            out.append("    {").append(q(fm)).append(", ").append(d(v)).append(", ").append(q(String.format(fm, v))).append("},\n");
        out.append("};\n");

        // ---- String.format (float argument)
        String[] ffmts = {"%f", "%.2f", "%.1f", "%s", "%e"};
        float[] fargs = {0.1f, 1.1f, 2.675f, 100.5f, 33.333332f, -0.15f};
        out.append("static const FormatFloatCase kFormatFloat[] = {\n");
        for (String fm : ffmts) for (float v : fargs)
            out.append("    {").append(q(fm)).append(", ").append(f(v)).append(", ").append(q(String.format(fm, v))).append("},\n");
        out.append("};\n");

        // ---- String.format (int / long argument)
        String[] ifmts = {"%d", "%5d", "%-5d|", "%05d", "%,d", "%+d", "% d", "%(d", "%x", "%X", "%08x", "%#x", "%o", "%#o", "%s", "%c", "%h", "%10s|", "%-10s|"};
        int[] iargs = {0, 1, -1, 42, -42, 1234567, Integer.MAX_VALUE, Integer.MIN_VALUE, 65, 255};
        out.append("static const FormatIntCase kFormatInt[] = {\n");
        for (String fm : ifmts) for (int v : iargs) {
            String r;
            try { r = String.format(fm, v); } catch (Exception e) { continue; }
            if (r.indexOf('\0') >= 0) continue;  // not representable as a C string
            out.append("    {").append(q(fm)).append(", ").append(v == Integer.MIN_VALUE ? "INT32_MIN" : String.valueOf(v)).append(", ").append(q(r)).append("},\n");
        }
        out.append("};\n");
        String[] lfmts = {"%d", "%x", "%o", "%,d", "%20d|", "%s"};
        long[] largs = {0L, -1L, 1234567890123L, Long.MAX_VALUE, Long.MIN_VALUE, -9876543210L};
        out.append("static const FormatLongCase kFormatLong[] = {\n");
        for (String fm : lfmts) for (long v : largs)
            out.append("    {").append(q(fm)).append(", ").append(v == Long.MIN_VALUE ? "INT64_MIN" : "INT64_C(" + v + ")").append(", ").append(q(String.format(fm, v))).append("},\n");
        out.append("};\n");
        // byte / short (Byte/Short arguments: %x uses the type width)
        out.append("static const FormatByteCase kFormatByte[] = {\n");
        byte[] bargs = {0, 1, -1, 127, -128, 16};
        for (String fm : new String[]{"%d", "%x", "%o", "%s"}) for (byte v : bargs)
            out.append("    {").append(q(fm)).append(", ").append(v).append(", ").append(q(String.format(fm, v))).append(", ").append(q(String.format(fm, (short) v))).append("},\n");
        out.append("};\n");

        // ---- String.format (String / misc)
        out.append("static const FormatMiscCase kFormatMisc[] = {\n");
        Object[][] misc = {
            {"%s %s", "a", "b"}, {"%2$s %1$s", "a", "b"}, {"%s %<s %s", "a", "b"}, {"%.2s", "abcdef"}, {"%S", "abc"},
            {"%-6s|%6s", "ab", "cd"}, {"%b %b %b", true, null, "x"}, {"%B", false}, {"%%d %n", 1}, {"%c%c", 'x', 'y'},
            {"%s", (Object) null}, {"[%5s]", (Object) null}, {"%10.3s|", "abcdef"}, {"x=%d y=%s", 5, "q"},
        };
        for (Object[] m : misc) {
            Object[] a = Arrays.copyOfRange(m, 1, m.length);
            out.append("    {").append(q((String) m[0])).append(", ").append(q(String.format((String) m[0], a))).append("},\n");
        }
        out.append("};\n");

        // ---- java.util.Random
        long[] seeds = {0L, 1L, 42L, -1L, 123456789L, Long.MIN_VALUE, 0x5DEECE66DL, 1234567890123456789L};
        out.append("static const RandomCase kRandom[] = {\n");
        for (long s : seeds) {
            Random r = new Random(s);
            out.append("    {").append(s == Long.MIN_VALUE ? "INT64_MIN" : "INT64_C(" + s + ")").append(", {");
            for (int i = 0; i < 5; i++) out.append(r.nextInt()).append(i < 4 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 5; i++) out.append(r.nextInt(100)).append(i < 4 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 5; i++) out.append(r.nextInt(1 << 20)).append(i < 4 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 5; i++) out.append(r.nextInt(1000000007)).append(i < 4 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 3; i++) out.append("INT64_C(").append(r.nextLong()).append(i < 2 ? "), " : ")");
            out.append("}, {");
            for (int i = 0; i < 5; i++) out.append(r.nextBoolean()).append(i < 4 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 3; i++) out.append(f(r.nextFloat())).append(i < 2 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 3; i++) out.append(d(r.nextDouble())).append(i < 2 ? ", " : "");
            out.append("}, {");
            for (int i = 0; i < 3; i++) out.append(d(r.nextGaussian())).append(i < 2 ? ", " : "");
            out.append("}, {");
            byte[] bs = new byte[7];
            r.nextBytes(bs);
            for (int i = 0; i < 7; i++) out.append(bs[i]).append(i < 6 ? ", " : "");
            out.append("}},\n");
        }
        out.append("};\n");

        // ---- String.hashCode / compareTo / case
        String[] hs = {"", "a", "abc", "Hello, World", "Привет", "한국어", "日本語テキスト", "emoji \uD83D\uDE00!", "Ünïcödé", "ß", "ΑΒΓ",
            "longer string with some text 1234567890"};
        out.append("static const StringCase kStrings[] = {\n");
        for (String s : hs)
            out.append("    {").append(q(s)).append(", ").append(s.hashCode()).append(", ").append(q(s.toUpperCase())).append(", ")
               .append(q(s.toLowerCase())).append(", ").append(s.length()).append("},\n");
        out.append("};\n");
        out.append("static const CompareCase kCompare[] = {\n");
        String[][] cmp = {{"a", "b"}, {"b", "a"}, {"abc", "ab"}, {"ab", "abc"}, {"", "x"}, {"Apple", "apple"}, {"apple", "Apple"},
            {"Привет", "Пока"}, {"a\uD83D\uDE00", "a\uFFFF"}, {"z", "Ω"}, {"same", "same"}, {"ABC", "abd"}};
        for (String[] c : cmp)
            out.append("    {").append(q(c[0])).append(", ").append(q(c[1])).append(", ").append(c[0].compareTo(c[1])).append(", ")
               .append(c[0].compareToIgnoreCase(c[1])).append(", ").append(c[0].equalsIgnoreCase(c[1])).append("},\n");
        out.append("};\n");

        // ---- String.split
        String[][] sp = {{"a,b,c", ","}, {"a,,b,,", ","}, {",a,b", ","}, {"", ","}, {"abc", ","}, {"a b  c", " "},
            {"a.b.c", "\\."}, {"a1b22c333d", "\\d+"}, {"  lead and trail  ", "\\s+"}, {"a|b|c", "\\|"}, {"key=value=x", "="},
            {"x--y--", "--"}, {"abc", ""}, {"1:2:3::", ":"}, {"a\tb\nc", "\\s"}, {"boo:and:foo", "o"}, {"aXbXc", "X"}};
        int[] limits = {0, -1, 2, 1, 5};
        out.append("static const SplitCase kSplit[] = {\n");
        for (String[] c : sp) for (int lim : limits) {
            String[] parts = c[0].split(c[1], lim);
            out.append("    {").append(q(c[0])).append(", ").append(q(c[1])).append(", ").append(lim).append(", ").append(parts.length).append(", {");
            for (int i = 0; i < parts.length; i++) out.append(q(parts[i])).append(i < parts.length - 1 ? ", " : "");
            out.append("}},\n");
        }
        out.append("};\n");

        // ---- replaceAll / replaceFirst / replace / matches / trim
        String[][] ra = {{"hello world", "o", "0"}, {"a1b2c3", "\\d", "#"}, {"John Smith", "(\\w+) (\\w+)", "$2, $1"},
            {"aaa", "a*", "X"}, {"abc", "", "-"}, {"tab\there", "\t", " "}, {"x.y.z", "\\.", "\\$"}, {"price: 10", "(\\d+)", "$1$1"},
            {"CamelCaseString", "([A-Z])", "_$1"}, {"  spaces  ", "^\\s+|\\s+$", ""}};
        out.append("static const ReplaceCase kReplace[] = {\n");
        for (String[] c : ra)
            out.append("    {").append(q(c[0])).append(", ").append(q(c[1])).append(", ").append(q(c[2])).append(", ")
               .append(q(c[0].replaceAll(c[1], c[2]))).append(", ").append(q(c[0].replaceFirst(c[1], c[2]))).append("},\n");
        out.append("};\n");

        // ---- Math.round
        float[] rf = {0.5f, -0.5f, 1.5f, -1.5f, 2.5f, -2.5f, 0.49999997f, -0.49999997f, 1e10f, -1e10f, Float.NaN, 3.4e38f, -3.4e38f, 0.0f, -0.0f, 12.3456f, 8388609.0f, 1e-45f};
        out.append("static const RoundFloatCase kRoundFloat[] = {\n");
        for (float v : rf) out.append("    {").append(f(v)).append(", ").append(Math.round(v) == Integer.MIN_VALUE ? "INT32_MIN" : String.valueOf(Math.round(v))).append("},\n");
        out.append("};\n");
        double[] rd = {0.5, -0.5, 1.5, -1.5, 2.5, -2.5, 0.49999999999999994, -0.49999999999999994, 1e19, -1e19, Double.NaN,
            4503599627370497.0, -4503599627370497.0, 0.0, 12.3456, 1e-300};
        out.append("static const RoundDoubleCase kRoundDouble[] = {\n");
        for (double v : rd) out.append("    {").append(d(v)).append(", ").append(Math.round(v) == Long.MIN_VALUE ? "INT64_MIN" : "INT64_C(" + Math.round(v) + ")").append("},\n");
        out.append("};\n");

        // ---- Integer.parseInt / decode / Long.parseLong
        String[] pi = {"0", "123", "-123", "+5", "2147483647", "-2147483648", "2147483648", "-2147483649", "", "-", "+", "12a",
            " 1", "1 ", "0x10", "007", "-0", "\uFF11\uFF12", "99999999999", "1_000"};
        out.append("static const ParseIntCase kParseInt[] = {\n");
        for (String s : pi) {
            String res; boolean ok;
            try { res = String.valueOf(Integer.parseInt(s)); ok = true; } catch (NumberFormatException e) { res = e.getMessage(); ok = false; }
            out.append("    {").append(q(s)).append(", 10, ").append(ok).append(", ").append(q(res)).append("},\n");
        }
        String[][] pir = {{"ff", "16"}, {"-FF", "16"}, {"7fffffff", "16"}, {"80000000", "16"}, {"-80000000", "16"}, {"z", "36"}, {"101", "2"},
            {"2", "2"}, {"g", "16"}, {"", "16"}, {"12", "1"}, {"12", "37"}};
        for (String[] c : pir) {
            String res; boolean ok;
            try { res = String.valueOf(Integer.parseInt(c[0], Integer.parseInt(c[1]))); ok = true; } catch (NumberFormatException e) { res = e.getMessage(); ok = false; }
            out.append("    {").append(q(c[0])).append(", ").append(c[1]).append(", ").append(ok).append(", ").append(q(res)).append("},\n");
        }
        out.append("};\n");
        String[] dec = {"0", "10", "-10", "0x1F", "0X1f", "#ff", "-#10", "010", "-010", "0", "+0x10", "0x80000000", "-0x80000000",
            "-2147483648", "08", "", "0x", "--1", "-+1", "0x-1", "2147483648"};
        out.append("static const ParseIntCase kDecode[] = {\n");
        for (String s : dec) {
            String res; boolean ok;
            try { res = String.valueOf(Integer.decode(s)); ok = true; } catch (NumberFormatException e) { res = e.getMessage(); ok = false; }
            out.append("    {").append(q(s)).append(", 0, ").append(ok).append(", ").append(q(res)).append("},\n");
        }
        out.append("};\n");
        String[] pl = {"0", "9223372036854775807", "-9223372036854775808", "9223372036854775808", "-9223372036854775809", "123456789012", "1L", "0x10"};
        out.append("static const ParseIntCase kParseLong[] = {\n");
        for (String s : pl) {
            String res; boolean ok;
            try { res = String.valueOf(Long.parseLong(s)); ok = true; } catch (NumberFormatException e) { res = e.getMessage(); ok = false; }
            out.append("    {").append(q(s)).append(", 10, ").append(ok).append(", ").append(q(res)).append("},\n");
        }
        out.append("};\n");
        String[] pb = {"127", "-128", "128", "-129", "0", "x"};
        out.append("static const ParseIntCase kParseByte[] = {\n");
        for (String s : pb) {
            String res; boolean ok;
            try { res = String.valueOf(Byte.parseByte(s)); ok = true; } catch (NumberFormatException e) { res = e.getMessage(); ok = false; }
            out.append("    {").append(q(s)).append(", 10, ").append(ok).append(", ").append(q(res)).append("},\n");
        }
        out.append("};\n");

        // ---- Double.parseDouble / Float.parseFloat
        String[] pd = {"1", "1.5", "-1.5", "+2.5", ".5", "5.", "1e10", "1E-5", "1.5f", "2d", "  3.25  ", "NaN", "-Infinity", "Infinity",
            "0x1p3", "0x1.8p1", "1e400", "1e-400", "4.9e-324", "", "abc", "1.2.3", "e5", "1e", "0.1", "3.4028235e38", "1e39", "0x10"};
        out.append("static const ParseDoubleCase kParseDouble[] = {\n");
        for (String s : pd) {
            String dr, fr; boolean dok, fok;
            try { double v = Double.parseDouble(s); dr = d(v); dok = true; } catch (NumberFormatException e) { dr = "0.0"; dok = false; }
            try { float v = Float.parseFloat(s); fr = f(v); fok = true; } catch (NumberFormatException e) { fr = "0.0f"; fok = false; }
            out.append("    {").append(q(s)).append(", ").append(dok).append(", ").append(dr).append(", ").append(fok).append(", ").append(fr).append("},\n");
        }
        out.append("};\n");

        // ---- Integer/Long string conversions
        int[] ic = {0, 1, -1, 255, -255, Integer.MAX_VALUE, Integer.MIN_VALUE, 0x7f3a9c, 1000000};
        out.append("static const IntStringCase kIntStrings[] = {\n");
        for (int v : ic)
            out.append("    {").append(v == Integer.MIN_VALUE ? "INT32_MIN" : String.valueOf(v)).append(", ").append(q(Integer.toString(v))).append(", ")
               .append(q(Integer.toHexString(v))).append(", ").append(q(Integer.toOctalString(v))).append(", ").append(q(Integer.toBinaryString(v))).append(", ")
               .append(q(Integer.toString(v, 36))).append(", ").append(Integer.bitCount(v)).append(", ").append(Integer.reverse(v)).append(", ")
               .append(Integer.reverseBytes(v)).append(", ").append(Integer.highestOneBit(v)).append(", ").append(Integer.numberOfLeadingZeros(v)).append(", ")
               .append(Integer.numberOfTrailingZeros(v)).append("},\n");
        out.append("};\n");
        long[] lc = {0L, -1L, 1234567890123L, Long.MAX_VALUE, Long.MIN_VALUE};
        out.append("static const LongStringCase kLongStrings[] = {\n");
        for (long v : lc)
            out.append("    {").append(v == Long.MIN_VALUE ? "INT64_MIN" : "INT64_C(" + v + ")").append(", ").append(q(Long.toString(v))).append(", ")
               .append(q(Long.toHexString(v))).append(", ").append(q(Long.toString(v, 7))).append(", ").append(Long.hashCode(v)).append("},\n");
        out.append("};\n");
        // Float/Double hex strings and hash codes
        out.append("static const HexFloatCase kHexDouble[] = {\n");
        for (double v : new double[]{0.0, 1.0, -2.5, 0.1, 4.9e-324, Double.MAX_VALUE, 1e-310})
            out.append("    {").append(d(v)).append(", ").append(q(Double.toHexString(v))).append(", ").append(Double.hashCode(v)).append("},\n");
        out.append("};\n");
        out.append("static const HexFloatFCase kHexFloat[] = {\n");
        for (float v : new float[]{0.0f, 1.0f, -2.5f, 0.1f, 1.4e-45f, Float.MAX_VALUE})
            out.append("    {").append(f(v)).append(", ").append(q(Float.toHexString(v))).append(", ").append(Float.hashCode(v)).append("},\n");
        out.append("};\n");

        System.out.print(out);
    }
}
