import java.io.*;
import java.util.*;
public class PropGen {
  static String[] cases = {
    "a=b\nc:d\ne f\n",
    "  key   =   value with trailing spaces   \n",
    "# comment\n! comment2\nk=v\n",
    "k=v\\\n   continued\n",
    "k=v\\\\\nx=y\n",
    "k\\ with\\ space=val\n",
    "k\\=eq=val\n",
    "unicode=\\u0041\\u00e9\\u4e2d\\uD83D\\uDE00\n",
    "bad=\\uZZZZ\n",
    "tabs\t=\tv\n\fformfeed=1\n",
    "noval\nnoval2=\n=emptykey\n:x\n",
    "k=v\r\nk2=v2\rk3=v3",
    "dup=1\ndup=2\n",
    "k=a\\tb\\nc\\rd\\fe\\qf\\\"g\\'\n",
    "k=\u00e9\u00ff\u0080\n\u00e8=x\n",
    "#comment\\\nk=v\n",
    "k=v\\\n\nz=1\n",
    "  \n\n   # indented comment\nk=v",
    "k = v1 \\\n  v2 \\\n v3\n",
    "k=v\\",
    "k\\\n=v\n",
    "x=\\u00",
    "a\\:b=c\n",
    "k  =  v\nk2  x = v\n",
    "k=\\u0020leading\n",
    "\\#notcomment=1\n",
    "  !comment?\nq=1",
    "k=v\\\r\n  next\n",
    "   \\\n k=v\n",
    "a=1\\\r\n\r\nb=2\n",
    "k\\\n  ey=va\\\n  lue\n",
    "\\\n\\\nk=v\n",
    "k=\\\n",
    "k=v\\\\\\\n x\n",
    "k\tv\nk2\fv2\n",
    "#only comment",
    "",
    "\n\n\n",
    "a=b\\u000Ac\n",
    "a=\\u00411\n",
    "a=b\\\n#notcomment\n",
    "a=b\\\n    \n",
    "a=\\\\u0041\n",
    "a=b\\ \n",
    "  a  \n",
    "a:=b\n",
    "a=:b\n",
    "a = = b\n",
    "a\\\\=b\n",
    "a\\\\\\=b=c\n",
    "!\\\nk=v\n",
    "k=v\r\r\n\nk2=v2\n",
    "\u0000key=\u0000val\n",
    "k=v\\\r",
    "k=v\\\rk2=v2\n",
    "x\\u0041y=1\n",
    "abc\\\n",
    "\\u0061=\\u0062\n",
    "a\\\nb\\\nc=d\n",
  };
  static String enc(String s) {
    StringBuilder b = new StringBuilder();
    for (char c : s.toCharArray()) {
      if (c >= 0x20 && c < 0x7f && c != '\\' && c != '|' && c != '"') b.append(c);
      else b.append(String.format("\\u%04x", (int) c));
    }
    return b.toString();
  }
  static String dump(Properties p) {
    TreeMap<String,String> m = new TreeMap<>();
    for (String k : p.stringPropertyNames()) m.put(k, p.getProperty(k));
    StringBuilder b = new StringBuilder();
    for (Map.Entry<String,String> e : m.entrySet()) b.append(enc(e.getKey())).append('=').append(enc(e.getValue())).append('|');
    return b.toString();
  }
  static String cstr(String s) { // chars 0..0xffff -> C++ u8 string literal of UTF-8? we emit raw bytes via octal (chars <=0xff only for stream cases)
    StringBuilder b = new StringBuilder("\"");
    byte[] bytes;
    try { bytes = s.getBytes("UTF-8"); } catch (Exception e) { throw new RuntimeException(e); }
    for (byte x : bytes) {
      int c = x & 0xff;
      if (c >= 0x20 && c < 0x7f && c != '\\' && c != '"' && c != '?') b.append((char) c);
      else b.append(String.format("\\%03o", c));
    }
    return b.append('"').toString();
  }
  static String cbytes(String s) {
    StringBuilder b = new StringBuilder("\"");
    for (char ch : s.toCharArray()) {
      int c = ch & 0xff;
      if (c >= 0x20 && c < 0x7f && c != '\\' && c != '"' && c != '?') b.append((char) c);
      else b.append(String.format("\\%03o", c));
    }
    return b.append('"').toString();
  }
  public static void main(String[] a) throws Exception {
    StringBuilder out = new StringBuilder();
    out.append("// Generated by PropGen.java (java.util.Properties on JDK 21). Do not edit.\n");
    out.append("struct PropCase { const char* input; int inputLen; const char* viaStream; const char* viaReader; };\n");
    out.append("static const PropCase kPropCases[] = {\n");
    for (String c : cases) {
      // via InputStream: chars are taken as ISO-8859-1 bytes
      byte[] bytes = c.getBytes("ISO-8859-1");
      String r1, r2;
      try { Properties p = new Properties(); p.load(new ByteArrayInputStream(bytes)); r1 = dump(p); } catch (Exception e) { r1 = "EX:" + e.getClass().getSimpleName(); }
      // via Reader: same bytes decoded as UTF-8 by the C++ side => use the UTF-8 string of c
      try { Properties p = new Properties(); p.load(new StringReader(c)); r2 = dump(p); } catch (Exception e) { r2 = "EX:" + e.getClass().getSimpleName(); }
      out.append("  {").append(cbytes(c)).append(", ").append(bytes.length).append(", ").append(cstr(r1)).append(", ").append(cstr(r2)).append("},\n");
    }
    out.append("};\n");
    // store() cases
    String[][] st = {
      {"key", "value"}, {"k e y", " v a l "}, {"a=b:c#d!e", "=:#!"}, {"tab\tnl\ncr\rff\f", "tab\tnl\ncr\rff\f"},
      {"\u00e9\u4e2d", "\u00e9\u4e2d\u0001"}, {"back\\slash", "back\\slash"}, {"", ""}, {"#", "!"}, {" ", " "}, {"x", "\uD83D\uDE00"}
    };
    out.append("struct StoreCase { const char* key; const char* value; const char* viaWriter; const char* viaStream; };\n");
    out.append("static const StoreCase kStoreCases[] = {\n");
    for (String[] kv : st) {
      Properties p = new Properties(); p.setProperty(kv[0], kv[1]);
      StringWriter w = new StringWriter(); p.store(w, null);
      String sw = w.toString(); sw = sw.substring(sw.indexOf('\n') + 1); // drop date line
      ByteArrayOutputStream bo = new ByteArrayOutputStream(); p.store(bo, null);
      String so = new String(bo.toByteArray(), "ISO-8859-1"); so = so.substring(so.indexOf('\n') + 1);
      out.append("  {").append(cstr(kv[0])).append(", ").append(cstr(kv[1])).append(", ").append(cstr(sw)).append(", ").append(cbytes(so)).append("},\n");
    }
    out.append("};\n");
    String[] comments = { "simple", " This file is machine-generated. DO NOT EDIT!", "multi\nline", "cr\r\nlf", "keep\n#hash", "keep\n!bang", "uni\u4e2d\u00e9", "end\n", "\r" };
    out.append("struct CommentCase { const char* comment; const char* viaWriter; };\n");
    out.append("static const CommentCase kCommentCases[] = {\n");
    for (String c : comments) {
      Properties p = new Properties();
      StringWriter w = new StringWriter(); p.store(w, c);
      String s = w.toString();
      // remove date line: the last line starting with '#' before entries; since no entries, remove last line
      String[] lines = s.split("\n", -1);
      StringBuilder b = new StringBuilder();
      for (int i = 0; i < lines.length - 2; i++) b.append(lines[i]).append('\n');
      out.append("  {").append(cstr(c)).append(", ").append(cstr(b.toString())).append("},\n");
    }
    out.append("};\n");
    System.out.print(out);
  }
}
