import java.util.*;
import java.util.regex.*;
public class RegexGen {
  static String[] pats = {
    "[a-zA-Z]{2,16}", "[a-zA-Z ]{2,16}", "[a-zA-Z]{2,25}", "[a-zA-Z]{2,10}", ".*{2,120}", ".*{2,255}", "a*{2}", "{2}",
    "\\d+", "\\w+\\s*", "(a|b)+c", "^abc$", "(?i)hello", "a.b", "a.*b", "\\p{Alpha}+", "\\p{L}+", "\\p{Lu}", "[a-z&&[^aeiou]]+", "[a-c[x-z]]+",
    "(?<name>\\d+)-\\k<name>", "a++b", "(?<=a)b", "\\Qa.b\\E", "x{2,}", "\\u0041", "\\x41", "\\0101", "[\\u0041-\\u0043]+", "$", "^", "(?m)^a$", "a$",
    "\\.", ",", ":", " ", "-", "/", "\\n", "\\s+", "[^,]+", "(\\w)(\\w)?", ".*AionLightning/", "(a)\\2", "\\1(a)", "(?s).+", "(?m)$", "(?m)^", "\\S+", "\\D", "\\W",
    "[\\s\\S]", "\\bword\\b", "\\B", "a|", "|a", "()", "(?:ab)+", "a{3}+", "a{2}{3}", "[]a]+", "[^]a]+", "\\p{Punct}+", "\\p{Digit}", "\\p{Upper}", "\\p{Lower}+", "\\p{Space}",
    "\\p{Alnum}+", "\\p{ASCII}+", "\\P{Alpha}+", "\\t", "\\e", "\\cA", "[a-]+", "[-a]+", "(?x) a b # c", "(?i:a)b", "\\z", "\\Z", "\\A", "a\\b", "[\\Q]\\E]+", "\\Q*\\E+",
    "(a)?b\\1", "((a)|b)+", "x*", "(?U)\\w+", "\\h+", "\\R", "[\\p{L}&&[^a-z]]+", "\\x{1F600}", "[^\\x00-\\x7f]+", "(?i)[a-z]+", "(?i)É", "é+", "\\s*,\\s*", "\\|", "\\\\",
    "(?d).", "(?d)^b", "(?d)a$", "a+?", "(a+)(b*)", "(?<!a)c", "(?>a+)b", "\\G\\w", "b*", "", "\\n?$", "\\r\\n", "[\\n\\r]+",
  };
  static String[] ins = {
    "", "a", "ab", "hello", "Hello World", "HELLO", "abc", "a\nb", "a\r\nb", "abc\n", "abc\r\n", "abc\r", "aaa", "aaab", "123-123", "12-34", "\u00e9", "\u00dcn\u00efc\u00f6d\u00e9", "x.y", "a.b",
    "AB", "ab ", " ab", "a\u2028b", "a\u0085b", "a\u000bb", "a,b,,c,,", ",a,,b", "one two  three", "key: value", "C:/Games/AionLightning/gs/data", "word words sword", "baab", "aab", "xyz abc", "\u00c9t\u00e9",
    "\uD83D\uDE00x", "a1_b2", "\t \n", "!!??..", "AbC", "bbc", "abab", "b", "ba", "a\n", "\n", "a|b\\c", "\u4e2d\u6587abc",
  };
  static String esc(String s) {
    StringBuilder b = new StringBuilder();
    for (char c : s.toCharArray()) {
      if (c >= 0x20 && c < 0x7f && c != '\\' && c != '"' && c != '|' && c != '[' && c != ']') b.append(c);
      else b.append(String.format("\\u%04x", (int) c));
    }
    return b.toString();
  }
  static boolean ascii(String s) { for (char c : s.toCharArray()) if (c > 127) return false; return true; }
  static String cstr(String s) {
    StringBuilder b = new StringBuilder("\"");
    byte[] bytes = s.getBytes(java.nio.charset.StandardCharsets.UTF_8);
    for (byte x : bytes) { int c = x & 0xff; if (c >= 0x20 && c < 0x7f && c != '\\' && c != '"' && c != '?') b.append((char) c); else b.append(String.format("\\%03o", c)); }
    return b.append('"').toString();
  }
  public static void main(String[] a) {
    StringBuilder out = new StringBuilder("// Generated by RegexGen.java (java.util.regex on JDK 21). Do not edit.\n");
    out.append("static const char* const kRegexPatterns[] = {\n");
    for (String p : pats) out.append("  ").append(cstr(p)).append(",\n");
    out.append("};\nstatic const char* const kRegexInputs[] = {\n");
    for (String s : ins) out.append("  ").append(cstr(s)).append(",\n");
    out.append("};\n// kRegexExpected[p * nInputs + i]\nstatic const char* const kRegexExpected[] = {\n");
    for (String p : pats) {
      Pattern pat;
      try { pat = Pattern.compile(p); } catch (PatternSyntaxException e) {
        for (String s : ins) out.append("  \"ERR\",\n");
        continue;
      }
      for (String s : ins) {
        StringBuilder r = new StringBuilder();
        Matcher m = pat.matcher(s);
        boolean asc = ascii(s);
        r.append("m").append(m.matches() ? 1 : 0);
        m.reset();
        r.append(" l").append(m.lookingAt() ? 1 : 0);
        m.reset();
        r.append(" f");
        int n = 0;
        while (m.find() && n < 8) {
          n++;
          r.append('[');
          if (asc) r.append(m.start()).append(',').append(m.end()).append(':');
          r.append(esc(m.group()));
          for (int g = 1; g <= m.groupCount(); g++) r.append('|').append(m.group(g) == null ? "null" : esc(m.group(g)));
          r.append(']');
        }
        r.append(" r:").append(esc(pat.matcher(s).replaceAll("<$0>")));
        r.append(" r1:").append(esc(pat.matcher(s).replaceFirst("_")));
        r.append(" s:");
        for (String x : pat.split(s)) r.append('[').append(esc(x)).append(']');
        r.append(" s-1:");
        for (String x : pat.split(s, -1)) r.append('[').append(esc(x)).append(']');
        r.append(" s2:");
        for (String x : pat.split(s, 2)) r.append('[').append(esc(x)).append(']');
        out.append("  ").append(cstr(r.toString())).append(",\n");
      }
    }
    out.append("};\n");
    System.out.print(out);
  }
}
